# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dataforgoodfr.github.io/covid_certificate_generator/"

git_url = "https://github.com/dataforgoodfr/covid_certificate_generator/tree/master/"

def custom_doc_links(name): return None
