# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PDFGenerator": "pdf_generator.ipynb",
         "PDF": "pdf_helper.ipynb"}

modules = ["pdf_generator.py",
           "pdf_helper.py"]

doc_url = "https://dataforgoodfr.github.io/covid_certificate_generator/"

git_url = "https://github.com/dataforgoodfr/covid_certificate_generator/tree/master/"

def custom_doc_links(name): return None
